
services:
  postgres:
    image: postgres:16.4-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54322:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  news-please:
    image: news-please:latest
    container_name: news-please
    volumes:
      - ./newsplease/config:/news-please/newsplease/config

volumes:
  postgres_data:
